/*
  BIANCA'S READING ROOM — ONE-TIME SUPABASE SETUP

  BEFORE RUNNING:
  Replace biancathewizz@gmail.com below with the email
  you will use for Supabase login. Use Replace All for every occurrence.
*/

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  cover_url text,
  cover_path text,
  rating numeric(2,1) not null check (rating >= 0 and rating <= 5),
  genre text,
  finished_date date,
  pages integer check (pages is null or pages >= 0),
  verdict text,
  review text not null,
  quote text,
  mood text,
  favorite boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.books enable row level security;

drop policy if exists "Public can read published books" on public.books;
create policy "Public can read published books"
on public.books for select
to anon, authenticated
using (
  published = true
  or lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

drop policy if exists "Only Bianca can add books" on public.books;
create policy "Only Bianca can add books"
on public.books for insert
to authenticated
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

drop policy if exists "Only Bianca can edit books" on public.books;
create policy "Only Bianca can edit books"
on public.books for update
to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
)
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

drop policy if exists "Only Bianca can delete books" on public.books;
create policy "Only Bianca can delete books"
on public.books for delete
to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'book-covers',
  'book-covers',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Only Bianca can upload covers" on storage.objects;
create policy "Only Bianca can upload covers"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'book-covers'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

drop policy if exists "Only Bianca can update covers" on storage.objects;
create policy "Only Bianca can update covers"
on storage.objects for update
to authenticated
using (
  bucket_id = 'book-covers'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
)
with check (
  bucket_id = 'book-covers'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

drop policy if exists "Only Bianca can delete covers" on storage.objects;
create policy "Only Bianca can delete covers"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'book-covers'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = lower('biancathewizz@gmail.com')
);

create index if not exists books_published_finished_idx
on public.books (published, finished_date desc);
